### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by 24-2021** [BlackSnufkin/NovaLdr#3]
Hello, sorry to bother you. This is a great project, but after I finished compiling, it failed to run. I changed the process to notepad. exe, which was the same error. After searching for some information, I found that it might be a problem with the Windows API "NtCreateUserProcess". I am not sure about the specifics because I do not know how to write the syntax format of "rust". Could you please help me solve this problem? Thank you very much

![image](https://github.com/BlackSnufkin/NovaLdr/assets/75511051/5b7a0373-0650-48be-b44b-9eb602a02e87)

**Comment by BlackSnufkin** [comment]
On which OS this is running on ?

**Comment by 24-2021** [comment]
![image](https://github.com/BlackSnufkin/NovaLdr/assets/75511051/73b9848c-89d7-4f74-ae89-129c3da360b8)


> On which OS this is running on ?

**Comment by BlackSnufkin** [comment]
there is an error in the working dir path or the exe path just try different process
